name: CustomBlocksApi
version: '${project.version}'
main: de.canstein_berlin.customblocksapi.CustomBlocksApiPlugin
api-version: 1.19

commands:
  convertToPlaceable:
    description: "Command to convert every Item to a placeable block"
  testplacement:
    description: "Test placement and performance"
  listCustomBlocks:
    description: "Command to show all registered custom blocks"