name: CustomBlocksApi
version: '${project.version}'
main: de.canstein_berlin.customblocksapi.CustomBlocksApiPlugin
api-version: 1.19

commands:
  listCustomBlocks:
    description: "Command to show all registered custom blocks"
  getCustomBlock:
    description: "Get a specific custom block"
  replaceCustomBlock:
    description: "Replaces a specified block in a Worldedit Region to custom blocks"